### ISSUE TITLE
solidity 转 java 失败 : not a valid name

### ISSUE THREAD

**Issue by teddycode** [FISCO-BCOS/console#380]
合约在webase上编写完成，但是用sol2java脚本转换时失败，日志输出只有not a valid name，其他啥都没有。

图1：在webase中编译通过，可部署调用。
![image](https://user-images.githubusercontent.com/21275020/95757475-c8b9fa00-0cd9-11eb-8a76-2ba16602f73d.png)

图2：sol2java转换失败。
![image](https://user-images.githubusercontent.com/21275020/95757524-d53e5280-0cd9-11eb-967f-bbc95040b029.png)

**Comment by ywy2090** [comment]
可以检查下合约的内容，`sol2java.sh`转换`contract`到`java`过程中，需要`Event`定义的每个变量都要有自己的名字
比如：
`Event sampleEvent(uint256)`，这种情况由于`uint256`下会出现`not a valid name`的错误，可以将Event定义修改为：
`Event sampleEvent(uint256 i)`即可。
