### ISSUE TITLE
建议callByCNS调用智能合约可以不指定版本号，默认调用最新版本智能合约

### ISSUE THREAD

**Issue by lilianwen** [FISCO-BCOS/console#46]
![image](https://user-images.githubusercontent.com/16525370/55524572-646bb280-56c0-11e9-9092-35a94f6fb372.png)
如上图所示，目前callByCNS调用智能合约的时候必须指定版本号，这显得很不智能。建议如下：
callByCNS可以不传版本号，这种情况下调用系统中该智能合约的最新版本；
callByCNS也可以指定版本号，直接调用该智能合约的指定版本，这样方便调用旧版本的智能合约。

**Comment by fqliao** [comment]
谢谢建议，在console 1.0.2版本进行支持。
