### ISSUE TITLE
3.0.0-rc4 版本 pro 链搭建之后，控制台启动报错

### ISSUE THREAD

**Issue by Youbaiwan** [FISCO-BCOS/console#650]
![image](https://user-images.githubusercontent.com/49031861/179650801-a0f198d7-160a-4429-8f85-0414a44a748c.png)

**Comment by kyonRay** [comment]
rc4和rc3协议不兼容，建议检查一下console的dist的lib目录下没有rc3的sdk、检查pro版本的二进制是否都升级了。

**Comment by Youbaiwan** [comment]
console lib 目录下 sdk 是  rc4 版本的，没有 rc3 版本。
![image](https://user-images.githubusercontent.com/49031861/179706829-774ceeac-2af0-4944-be3e-9293afc42de9.png)

pro版本中，rpc服务相关的二进制是 rc3 版本的， 需要升级到 rc4 版本吗？
![image](https://user-images.githubusercontent.com/49031861/179709379-77bd2100-d14d-4078-ab13-e0a74e7a684c.png)

**Comment by kyonRay** [comment]
> console lib 目录下 sdk 是 rc4 版本的，没有 rc3 版本。 ![image](https://user-images.githubusercontent.com/49031861/179706829-774ceeac-2af0-4944-be3e-9293afc42de9.png)
> 
> pro版本中，rpc服务相关的二进制是 rc3 版本的， 需要升级到 rc4 版本吗？ ![image](https://user-images.githubusercontent.com/49031861/179709379-77bd2100-d14d-4078-ab13-e0a74e7a684c.png)

是的，协议不兼容就是网络层的协议不兼容，建议所有二进制都升级到rc4。
兼容性参考：https://github.com/FISCO-BCOS/FISCO-BCOS/releases/tag/v3.0.0-rc4

**Comment by Youbaiwan** [comment]
好的 ，谢谢。昨天升级 RPC 服务之后，控制台可以正常启动了。

之前的二进制版本是按照文档，由 cdn 下载通道下载的（https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/FISCO-BCOS/FISCO-BCOS/releases/v3.0.0-rc4/BcosRpcService-linux-x86_64.tgz），下载下来是 rc3 版本。
