### ISSUE TITLE
在FISCO 3.x上搭建群/环签名后在命令行调用预编译合约失败

### ISSUE THREAD

**Issue by yeyuexiaofeng** [FISCO-BCOS/console#786]
FISCO版本为 3.x   群/环签名客户端版本为 3.x 
此前搭建过2.x版本，按照官方文档可以正确调用预编译合约，在重新搭建3.x版本时，调用预编译合约显示 "Abi is empty, please check contract abi exists"

**Comment by kyonRay** [comment]
感谢提出issue，在2.0的控制台在调用时会再次编译合约获取ABI，3.0的控制台没有这个步骤。在下个版本会加上。

**Comment by yeyuexiaofeng** [comment]
好的 谢谢

**Comment by kyonRay** [comment]
#787
